import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import store from './store';
import {getChildrenByID} from './actions/content';
window.getChildrenByID = getChildrenByID;
ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
